services:
  - type: web
    name: ets-rag-chatbot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: MONGODB_URI
        sync: false
      - key: MONGODB_DBNAME
        value: rag_chatbot
      - key: OPENAI_API_KEY
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: OPENAI_CHAT_MODEL
        value: gpt-4o-mini
      - key: EMBEDDING_MODEL
        value: text-embedding-3-small
      - key: RETRIEVAL_TOP_K
        value: 5
      - key: RETRIEVAL_SCORE_MIN
        value: 0.7
      - key: CHROMA_PERSIST_DIR
        value: ./chroma_db
